name: Hello World Wo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Hello World
        run: echo "Hello World From Nuredin Bedru"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World From Nuredin Bedru"
        shell: bash
