name: Comment on Newly Created Issue

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Grants permission to write comments on issues

jobs:
  # Job 1: Comment using 'peter-evans/create-or-update-comment'
  comment_on_new_issues_using_Actions:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Log GitHub context (for debugging)
      - name: Get GitHub Context (Debugging)
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      
      # Step 2: Create a comment using the peter-evans action
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello! 👋
            
            Thank you for opening this issue. We appreciate your feedback and will review it as soon as possible.

            - This comment was created using **peter-evans/create-or-update-comment**! 🚀

  # Job 2: Comment using GitHub API
  comment_on_issue_using_api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Post a comment using GitHub API
      - name: Post Comment Using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this token automatically
        run: |
          curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d @- << EOF
          {
            "body": "Hello! 👋\n\nThank you for opening this issue. We appreciate your feedback and will review it as soon as possible AND IT COMES FROM API.\n\n- This comment was posted using the **GitHub API**! 🚀"
          }
          EOF
